### ISSUE TITLE
TOY dataset not downloadable

### ISSUE THREAD

**Issue by aimirza** [donia-lab/MetaBGC#15]
Hi,

The Toy dataset does not download.

ALi

**Comment by abiswas-odu** [comment]
You are not able to download the file linked in this section? https://github.com/donia-lab/MetaBGC#quick-start 

It points to a public google drive file. The naked URL is: https://drive.google.com/file/d/1-6nhr7WpWFbAxj89F-Q4fmB83nBhBDI-/view?usp=sharing
