### ISSUE TITLE
Search does not run Quantify and Cluster

### ISSUE THREAD

**Issue by aimirza** [donia-lab/MetaBGC#17]
Using release 2, it seems that metabgc search ends at the Identify step. It didn't run Quantify or Cluster. Here is the last two lines of the output:

```
Metabgc-identify HMMER search is complete.
Metabgc-identify has failed. Please check your inputs and contact support on : https://github.com/donia-lab/MetaBGC
```

My command:

metabgc search --sphmm_directory /home/amirza/MetaBGC/MetaBGC/MetaBGC-V1/MetaBGC-Build_Outputs/Cyclase_TcmI --nucl_seq_directory ~/biobakery/kneaddata/final/test --seq_fmt FASTQ --pair_fmt split --r1_file_suffix repeats.removed.all.1.fastq --r2_file_suffix  repeats.removed.all.2.fastq --prot_family_name Cyclase_TcmI --cohort_name TcmI --output_directory /home/amirza/MetaBGC/test --cpu 16

FYI, I had to change file extension name ".txt" to ".tsv" of the Cyclase_TcmI_F1_Cutoff.txt of because of the error I received (below) in a previous run. I dont think this was an issue for Cyclase_OxyN. 

`Metabgc-identify did not find the spHMM cutoff threshold file at the expected location.:/home/amirza/MetaBGC/MetaBGC/MetaBGC-V1/MetaBGC-Build_Outputs/Cyclase_TcmI/Cyclase_TcmI_F1_Cutoff.tsv`

**Comment by abiswas-odu** [comment]
Looks like we have to re-generate the model cutoff metadata file for the other 3 cyclase. We changed to format of the file and added some columns.

**Comment by aimirza** [comment]
So is there a problem using the other 3 cyclases currently?

**Comment by abiswas-odu** [comment]
I successfully tested a run of TcmI with the model build directories provided here [https://github.com/donia-lab/MetaBGC/tree/master/Models](https://github.com/donia-lab/MetaBGC/tree/master/Models). Please use the build directories provided here. They are the same spHMMs as the publication with updated cutoff file format that works with later versions of MetaBGC.

**Comment by aimirza** [comment]
Worked with no apparent issues. Thanks!
