### ISSUE TITLE
Input files unclear

### ISSUE THREAD

**Issue by susheelbhanu** [donia-lab/MetaBGC#23]
Hi, 

Thanks for a promising tool. However, from the description, it sounds like the tool can run on `metagenomic assemblies`. Whereas the downstream description sounds like it can only take reads.

Could you please clarify whether it takes reads, MAGs (genomes), and/or metagenomic assemblies?

Thank you!

**Comment by abiswas-odu** [comment]
```metabgc search``` only takes reads. Assemblies can be used in the last ```metabgc analytics``` step to extract scaffolds that contain the identified reads. ```metabgc synthesize``` takes assemblies of to create the dataset for building spHMM models for a new protein family.

**Comment by susheelbhanu** [comment]
Could you please provide a reproducible example for each of these steps in the listed order? It will also help to have a test set of reads as an example. Just a thought, to make it more user-friendly.

More importantly, it is unclear whether one can run the `metabgc analytics` step without running the `metabgc search`. 

Thanks!

**Comment by abiswas-odu** [comment]
Toy datasets are provided in [Quick Start](https://github.com/donia-lab/MetaBGC#quick-start) for both search and build. A successful search must be performed before you can run analytics on the output.

**Comment by susheelbhanu** [comment]
Great, thank you!
