### ISSUE TITLE
codon table

### ISSUE THREAD

**Issue by alienzj** [donia-lab/MetaBGC#3]
https://github.com/donia-lab/MetaBGC/blob/2c8741f43c296b8d4826edcd9c179ad0a19a7a7e/MetaBGC-V1/MetaBGC-V1_Scripts/Utils/Utils.py#L132

Hello, why not use codon table 11 for bacterial?
The HMP ane MetaHIT samples has removed all host sequences.

**Comment by abiswas-odu** [comment]
Good suggestion. I will make the change in the 1.2 update.
