### ISSUE TITLE
prot_seq_directory flag required?

### ISSUE THREAD

**Issue by Manoo-hao** [donia-lab/MetaBGC#5]
Is it possible that --prot_seq_directory is required at least for metabgc identify?

**Comment by abiswas-odu** [comment]
Are you receiving an error if you do not specify it? You will need to have transeq in path if the directory is not specified.

**Comment by Manoo-hao** [comment]
Yes, I receive the following error after a string of tracebacks if I do not specify --prot_seq_directory:
![image](https://user-images.githubusercontent.com/10657025/73487489-fa20bd00-440b-11ea-970b-44c860128414.png)
I'll look into transeq and give it another go.

**Comment by abiswas-odu** [comment]
Thanks for the snapshot. Fixed in development branch. Will release to PYPI soon.

**Comment by maxibor** [comment]
Same issue here with @xentrics
