### ISSUE TITLE
Toy input files for build operation

### ISSUE THREAD

**Issue by deucy646** [donia-lab/MetaBGC#8]
Can you provide the toy input files for build operation to test and run build for MetaBGC v1.3.3.

**Comment by abiswas-odu** [comment]
The build operation requires creating a synthetic read dataset with background and true positive genomes. The process is described in the publication and the accession numbers of genomes used for the protein families is provided. The user needs to create this synthetic dataset as described in the publication.

**Comment by Manoo-hao** [comment]
In the supplementary materials you describe how to generate two synthetic metagenomes, and then in the evaluation section mention that you "used [your] constructed synthetic dataset to evaluate the performance of [your] spHMMs". Which of the two synthetic datasets did you use?

**Comment by abiswas-odu** [comment]
We used the second one. Please see new paragraph in constructing synthetic datasets here: https://github.com/donia-lab/MetaBGC#running-build-to-construct-the-sphmms 

I added the other models we have here: https://github.com/donia-lab/MetaBGC/tree/master/Models

**Comment by abiswas-odu** [comment]
CORRECTION: We used both the synthetic sets. Please see figure S7 and S11 in the supplementary file of the paper. They contain the same genomes, just different ratios of the spiked positives versus the background negatives.
